# Travis CI configuration for the acis library.
#
# The Travis CI service verifies each GitHub commit for correctness.
# <http://travis-ci.org>


# Language specifications

language: php
php:
    - 5.2
    - 5.3
    - 5.4

# Test script

script: php -f test/test_acis.php


# Branch restrictions

branches:
    only:
        - master
        - dev
